// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAydQRB2u2s2VnEUOL47rY5dhaU0gX1r58',
    appId: '1:554187940881:web:5c9f1c8d6c236d84427db0',
    messagingSenderId: '554187940881',
    projectId: 'street-calle-72cff',
    authDomain: 'street-calle-72cff.firebaseapp.com',
    storageBucket: 'street-calle-72cff.appspot.com',
    measurementId: 'G-WJB0K0E9Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_NMd-RkaBZ1TkmB6M08BefczCZymjY10',
    appId: '1:554187940881:android:defc7f6858577e30427db0',
    messagingSenderId: '554187940881',
    projectId: 'street-calle-72cff',
    storageBucket: 'street-calle-72cff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0YOiTNZAGz2I28aacOtIVuVHPYWDRiPY',
    appId: '1:554187940881:ios:ed7c25b597478d3c427db0',
    messagingSenderId: '554187940881',
    projectId: 'street-calle-72cff',
    storageBucket: 'street-calle-72cff.appspot.com',
    androidClientId: '554187940881-8vp48rtqdtve7tp1u8djf8pue854dgaa.apps.googleusercontent.com',
    iosClientId: '554187940881-8kg434k628ri89o4jkchgmu54qbr7qhh.apps.googleusercontent.com',
    iosBundleId: 'com.developlogix.streetcalle.streetCalleFlutter',
  );
}
